require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaskdependentsController do

  # This should return the minimal set of attributes required to create a valid
  # Taskdependent. As you add validations to Taskdependent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "task_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaskdependentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all taskdependents as @taskdependents" do
      taskdependent = Taskdependent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taskdependents).should eq([taskdependent])
    end
  end

  describe "GET show" do
    it "assigns the requested taskdependent as @taskdependent" do
      taskdependent = Taskdependent.create! valid_attributes
      get :show, {:id => taskdependent.to_param}, valid_session
      assigns(:taskdependent).should eq(taskdependent)
    end
  end

  describe "GET new" do
    it "assigns a new taskdependent as @taskdependent" do
      get :new, {}, valid_session
      assigns(:taskdependent).should be_a_new(Taskdependent)
    end
  end

  describe "GET edit" do
    it "assigns the requested taskdependent as @taskdependent" do
      taskdependent = Taskdependent.create! valid_attributes
      get :edit, {:id => taskdependent.to_param}, valid_session
      assigns(:taskdependent).should eq(taskdependent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Taskdependent" do
        expect {
          post :create, {:taskdependent => valid_attributes}, valid_session
        }.to change(Taskdependent, :count).by(1)
      end

      it "assigns a newly created taskdependent as @taskdependent" do
        post :create, {:taskdependent => valid_attributes}, valid_session
        assigns(:taskdependent).should be_a(Taskdependent)
        assigns(:taskdependent).should be_persisted
      end

      it "redirects to the created taskdependent" do
        post :create, {:taskdependent => valid_attributes}, valid_session
        response.should redirect_to(Taskdependent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taskdependent as @taskdependent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taskdependent.any_instance.stub(:save).and_return(false)
        post :create, {:taskdependent => { "task_id" => "invalid value" }}, valid_session
        assigns(:taskdependent).should be_a_new(Taskdependent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taskdependent.any_instance.stub(:save).and_return(false)
        post :create, {:taskdependent => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taskdependent" do
        taskdependent = Taskdependent.create! valid_attributes
        # Assuming there are no other taskdependents in the database, this
        # specifies that the Taskdependent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Taskdependent.any_instance.should_receive(:update_attributes).with({ "task_id" => "1" })
        put :update, {:id => taskdependent.to_param, :taskdependent => { "task_id" => "1" }}, valid_session
      end

      it "assigns the requested taskdependent as @taskdependent" do
        taskdependent = Taskdependent.create! valid_attributes
        put :update, {:id => taskdependent.to_param, :taskdependent => valid_attributes}, valid_session
        assigns(:taskdependent).should eq(taskdependent)
      end

      it "redirects to the taskdependent" do
        taskdependent = Taskdependent.create! valid_attributes
        put :update, {:id => taskdependent.to_param, :taskdependent => valid_attributes}, valid_session
        response.should redirect_to(taskdependent)
      end
    end

    describe "with invalid params" do
      it "assigns the taskdependent as @taskdependent" do
        taskdependent = Taskdependent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taskdependent.any_instance.stub(:save).and_return(false)
        put :update, {:id => taskdependent.to_param, :taskdependent => { "task_id" => "invalid value" }}, valid_session
        assigns(:taskdependent).should eq(taskdependent)
      end

      it "re-renders the 'edit' template" do
        taskdependent = Taskdependent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taskdependent.any_instance.stub(:save).and_return(false)
        put :update, {:id => taskdependent.to_param, :taskdependent => { "task_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taskdependent" do
      taskdependent = Taskdependent.create! valid_attributes
      expect {
        delete :destroy, {:id => taskdependent.to_param}, valid_session
      }.to change(Taskdependent, :count).by(-1)
    end

    it "redirects to the taskdependents list" do
      taskdependent = Taskdependent.create! valid_attributes
      delete :destroy, {:id => taskdependent.to_param}, valid_session
      response.should redirect_to(taskdependents_url)
    end
  end

end
